services:
  - type: web
    name: solar-power-prediction-api
    env: python
    region: oregon
    buildCommand: "pip install -r summative/API/requirements.txt"
    startCommand: "uvicorn summative.API.prediction:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
